import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { SSAOPass } from 'three/addons/postprocessing/SSAOPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const viewport=$('#viewport'),mobile=matchMedia('(max-width:800px)').matches;
let renderer,model,controls,activeCamera,night=false,bodyMats=[],glassMats=[],allMats=[],rotors=[],podGroups=[],paint='#b7c0ca',toastTimer,ready=false;
const scene=new THREE.Scene(),pivot=new THREE.Group();scene.add(pivot);
const perspective=new THREE.PerspectiveCamera(35,1,.03,150),orthographic=new THREE.OrthographicCamera(-4,4,3,-3,.03,150);activeCamera=perspective;
const target=new THREE.Vector3(0,1.04,0),clock=new THREE.Clock();
function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,3000)}
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.5:2));renderer.setClearColor('#eeeae4');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive three-dimensional AEROVANE V4 concept. Drag to rotate and pinch or scroll to zoom.');renderer.domElement.setAttribute('tabindex','0');}
catch(e){$('#loading').hidden=true;$('#webglerror').hidden=false;$('#status').textContent='3D unavailable — proposal and model downloads available';throw e}
const composer=new EffectComposer(renderer);const occlusionPass=new SSAOPass(scene,perspective,1,1,16);occlusionPass.kernelRadius=12;occlusionPass.minDistance=.002;occlusionPass.maxDistance=.08;composer.addPass(occlusionPass);composer.addPass(new OutputPass());$('#occlusion').checked=!mobile;
function drawScene(){if($('#occlusion').checked&&!sketch&&activeCamera===perspective){occlusionPass.camera=activeCamera;composer.render()}else renderer.render(scene,activeCamera)}
// Classic cube reflections for Phong chrome; no PBR environment or texture atlas.
const reflectionScene=new THREE.Scene();reflectionScene.background=new THREE.Color(0x67747f);
for(const [x,y,z,sx,sy,sz] of [[0,5,0,9,.1,8],[-5,1,0,.1,4,9],[4,2,2,.1,3,7],[0,0,-5,6,3,.1]]){const panel=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshBasicMaterial({color:0xe9f0f4}));panel.position.set(x,y,z);reflectionScene.add(panel)}
const reflectionTarget=new THREE.WebGLCubeRenderTarget(128);const reflectionCamera=new THREE.CubeCamera(.1,30,reflectionTarget);reflectionCamera.update(renderer,reflectionScene);
const reflectionMap=reflectionTarget.texture;
let sketch=false,sketchStyle='paper',editable=[],edgeObjects=[],outlineObjects=[];
const defaults=[{color:'#e2e5e4',shine:85,reflect:15,opacity:100},...Array.from({length:4},()=>({color:'#d7e1e3',shine:105,reflect:20,opacity:100})),{color:'#87949e',shine:165,reflect:55,opacity:100},{color:'#000000',shine:230,reflect:45,opacity:100},{color:'#303d44',shine:65,reflect:30,opacity:100}];
let configs=structuredClone(defaults);
try{const saved=JSON.parse(localStorage.getItem('aerovane-v4-materials-v1'));if(Array.isArray(saved)&&saved.length===8&&saved.every(v=>/^#[0-9a-f]{6}$/i.test(v.color)&&['shine','reflect','opacity'].every(k=>Number.isFinite(v[k]))))configs=saved}catch{}
const bands=new THREE.DataTexture(new Uint8Array([110,170,220,255]),4,1,THREE.RedFormat);bands.needsUpdate=true;bands.minFilter=bands.magFilter=THREE.NearestFilter;
const sketchMat=new THREE.MeshToonMaterial({color:0xf8f4e9,gradientMap:bands,side:THREE.DoubleSide});
const edgeMat=new THREE.LineBasicMaterial({color:0x28333c,transparent:true,opacity:.72});
const outlineMat=new THREE.ShaderMaterial({uniforms:{ink:{value:new THREE.Color(0x26333d)},width:{value:.005}},vertexShader:'uniform float width; void main(){gl_Position=projectionMatrix*modelViewMatrix*vec4(position+normal*width,1.0);}',fragmentShader:'uniform vec3 ink; void main(){gl_FragColor=vec4(ink,1.0);}',side:THREE.BackSide});
function saveMaterials(){try{localStorage.setItem('aerovane-v4-materials-v1',JSON.stringify(configs))}catch{}}
function applyMaterials(){configs.forEach((c,i)=>{const m=editable[i];if(!m)return;m.color.set(c.color);m.shininess=c.shine;m.reflectivity=c.reflect/100;m.opacity=c.opacity/100;m.transparent=c.opacity<100;m.depthWrite=c.opacity>=100;m.envMap=c.reflect>0?reflectionMap:null;m.specular.setScalar(i===6?.85:.5);m.needsUpdate=true});saveMaterials()}
function syncEditor(){const c=configs[+$('#part').value];$('#matColor').value=c.color;$('#shine').value=c.shine;$('#shineVal').textContent=c.shine;$('#reflect').value=c.reflect;$('#reflectVal').textContent=c.reflect+'%';$('#opacity').value=c.opacity;$('#opacityVal').textContent=c.opacity+'%'}
function setSketch(on){sketch=on;document.body.classList.toggle('night',on?sketchStyle!=='paper':night);$('#sketch').classList.toggle('selected',on);$('#sketch').setAttribute('aria-pressed',String(on));$('#sketchTools').hidden=!on;model?.traverse(o=>{if(o.userData.classicMaterial)o.material=on?sketchMat:o.userData.classicMaterial});edgeObjects.forEach(o=>o.visible=on);outlineObjects.forEach(o=>o.visible=on);floor.visible=!on;stage.visible=night&&!on;key.castShadow=!on;const colors={paper:[0xf3efe5,0x26333d,0xf8f4e9],blueprint:[0x122c48,0xb2ddff,0x37618b],graphite:[0x20252c,0xe2e7ea,0x646e78]}[sketchStyle];if(on){scene.background=new THREE.Color(colors[0]);scene.fog.color.set(colors[0]);sketchMat.color.set(colors[2]);edgeMat.color.set(colors[1]);outlineMat.uniforms.ink.value.set(colors[1]);$('#status').textContent='SKETCH / '+sketchStyle.toUpperCase();}else atmosphere(night)}
const hemi=new THREE.HemisphereLight(0xdcecff,0x454447,1);scene.add(hemi);
const key=new THREE.DirectionalLight(0xfff6e8,4);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(key.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:20});key.shadow.normalBias=.025;key.shadow.bias=-.0001;scene.add(key);
const rim=new THREE.DirectionalLight(0xc0dfff,2.1);rim.position.set(4,3,-5);scene.add(rim);
const fill=new THREE.DirectionalLight(0xffffff,1.2);fill.position.set(-5,2,-3);scene.add(fill);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshPhongMaterial({color:0xeeeae4,shininess:8}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;floor.position.y=-.01;scene.add(floor);scene.fog=new THREE.Fog(0xeeeae4,17,45);
const stage=new THREE.Group();scene.add(stage);stage.visible=false;
const disk=new THREE.Mesh(new THREE.CylinderGeometry(3.45,3.45,.05,128),new THREE.MeshPhongMaterial({color:0x111b28,shininess:95,specular:0x63778a}));disk.position.y=-.045;disk.receiveShadow=true;stage.add(disk);
const glowMaterial=new THREE.MeshBasicMaterial({color:0x9acde5,toneMapped:false});
function ring(radius,width,y){const m=new THREE.Mesh(new THREE.RingGeometry(radius-width,radius,128),glowMaterial);m.rotation.x=-Math.PI/2;m.position.y=y;stage.add(m)}ring(3.37,.018,.001);ring(1.82,.025,.003);
// AEROVANE mark: four separated lift stations around a double-chevron keel.
for(const [x,z] of [[-1.25,1.1],[1.25,1.1],[-1.25,-1.1],[1.25,-1.1]]){const q=new THREE.Mesh(new THREE.RingGeometry(.15,.18,32),glowMaterial);q.rotation.x=-Math.PI/2;q.position.set(x,.008,z);stage.add(q)}
const markPoints=[[-.7,-.75],[0,.85],[.7,-.75],[.42,-.75],[0,.23],[-.42,-.75]];const mark=new THREE.Shape(markPoints.map(p=>new THREE.Vector2(...p)));const emblem=new THREE.Mesh(new THREE.ShapeGeometry(mark),glowMaterial);emblem.rotation.x=-Math.PI/2;emblem.position.y=.005;stage.add(emblem);
const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');let grad=ctx.createRadialGradient(128,128,0,128,128,128);grad.addColorStop(0,'rgba(92,177,228,.45)');grad.addColorStop(.4,'rgba(48,135,210,.15)');grad.addColorStop(1,'rgba(20,90,200,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,256,256);const glow=new THREE.Mesh(new THREE.PlaneGeometry(8.5,8.5),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false}));glow.rotation.x=-Math.PI/2;glow.position.y=.006;stage.add(glow);
const under=new THREE.PointLight(0x65bfff,0,5,2);under.position.set(0,.2,0);scene.add(under);
function makeControls(){if(controls)controls.dispose();controls=new OrbitControls(activeCamera,renderer.domElement);controls.target.copy(target);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=4;controls.maxDistance=19;controls.maxPolarAngle=Math.PI*.49;controls.minZoom=.55;controls.maxZoom=2.8;controls.enablePan=true;controls.update()}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight,a=w/h;renderer.setSize(w,h,false);composer.setSize(w,h);perspective.aspect=a;perspective.updateProjectionMatrix();const f=mobile?3.8:3.4;orthographic.left=-f*a;orthographic.right=f*a;orthographic.top=f;orthographic.bottom=-f;orthographic.updateProjectionMatrix()}
new ResizeObserver(resize).observe(viewport);
const views={hero:[-7,3.7,8.6],low:[-6.8,1.6,8.5],detail:[-4.2,2.2,4.5],side:[-10,1.05,0],front:[0,1.05,10],rear:[0,1.05,-10],top:[0,11,.001],other:[10,1.05,0]};
function view(name){pivot.rotation.y=0;$('#turn').checked=false;activeCamera=['hero','low','detail'].includes(name)?perspective:orthographic;const v=views[name];activeCamera.position.set(...v);if(name==='hero'&&mobile)activeCamera.position.multiplyScalar(1.05);orthographic.zoom=1;activeCamera.up.set(0,1,0);if(name==='top')activeCamera.up.set(0,0,-1);makeControls();resize();activeCamera.lookAt(target);all('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===name));$('#viewLabel').textContent=['hero','low','detail'].includes(name)?'PERSPECTIVE / '+name.toUpperCase():'ORTHOGRAPHIC / '+name.toUpperCase();$('#yaw').value=0;$('#yawVal').textContent='0°'}
view('hero');
const loading=new THREE.LoadingManager();loading.onProgress=(url,loaded,total)=>$('#progress').textContent=`Preparing surfaces ${loaded} / ${total}`;
const loader=new GLTFLoader(loading);
loader.load('assets/AEROVANE-V4.glb',gltf=>{model=gltf.scene;const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const scale=1;model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);pivot.add(model);const originalMaterials=new Map();const pending=[];
model.traverse(o=>{if(o.isMesh)pending.push(o);if(o.name.startsWith('Rotor_'))rotors.push(o);if(/^0[2-5]_Pod/.test(o.name))podGroups.push(o)});
const names=['Framework','Pod_FL','Pod_FR','Pod_RL','Pod_RR','Fans','Windshield','Structure'];
for(const o of pending){o.castShadow=true;o.receiveShadow=true;const original=o.material;const i=Math.max(0,names.findIndex(n=>original.name.startsWith(n)));if(!editable[i]){editable[i]=new THREE.MeshPhongMaterial({name:names[i],side:THREE.DoubleSide,color:configs[i].color,shininess:configs[i].shine});allMats.push(editable[i])}o.material=editable[i];o.userData.classicMaterial=o.material;
const edges=new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,38),edgeMat);edges.visible=false;o.add(edges);edgeObjects.push(edges);
const outline=new THREE.Mesh(o.geometry,outlineMat);outline.visible=false;o.add(outline);outlineObjects.push(outline);originalMaterials.set(original.uuid,original)}
originalMaterials.forEach(m=>m.dispose());applyMaterials();syncEditor();
ready=true;$('#loading').hidden=true;$('#status').textContent='SIX ASSEMBLIES / FOUR AXIAL ROTORS';setSketch(sketch);},xhr=>{if(xhr.total)$('#progress').textContent=`Loading model · ${Math.round(xhr.loaded/xhr.total*100)}%`},e=>{console.error(e);$('#loading').hidden=true;$('#webglerror').hidden=false;$('#status').textContent='Model loading failed';toast('Could not load model. Please reload or use the GLB download.')});
function atmosphere(isNight){night=isNight;document.body.classList.toggle('night',night);$('#night').classList.toggle('selected',night);$('#studio').classList.toggle('selected',!night);stage.visible=night&&!sketch;scene.background=new THREE.Color(night?0x080d14:0xeeeae4);scene.fog.color.copy(scene.background);floor.material.color.set(night?0x090f19:0xeeeae4);key.intensity=night?1.5:2;rim.intensity=night?1.8:1.1;fill.intensity=night?.4:.7;hemi.intensity=night?.32:1;under.intensity=night?2.5:0;$('#status').textContent=night?'NOCTURNE / AEROVANE FLIGHT DECK':'STUDIO / CLASSIC MATERIALS'}
$('#night').onclick=()=>{atmosphere(true);if(sketch)setSketch(true)};$('#studio').onclick=()=>{atmosphere(false);if(sketch)setSketch(true)};
all('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#sketch').onclick=()=>setSketch(!sketch);$('#sketchStyle').onchange=e=>{sketchStyle=e.target.value;setSketch(true)};$('#inkWidth').oninput=e=>{outlineMat.uniforms.width.value=Number(e.target.value)/2000};
$('#part').onchange=syncEditor;
for(const [id,key] of [['matColor','color'],['shine','shine'],['reflect','reflect'],['opacity','opacity']])$('#'+id).oninput=e=>{configs[+$('#part').value][key]=key==='color'?e.target.value:+e.target.value;applyMaterials();syncEditor()};
$('#preset').onchange=e=>{const i=+$('#part').value,c=configs[i],presets={gloss:[120,35],satin:[35,12],matte:[5,0],chrome:[200,90]};if(presets[e.target.value]){[c.shine,c.reflect]=presets[e.target.value];if(e.target.value==='chrome')c.color='#c6ced6';applyMaterials();syncEditor()}};
$('#resetMaterial').onclick=()=>{const i=+$('#part').value;configs[i]=structuredClone(defaults[i]);applyMaterials();syncEditor()};
$('#exportMaterials').onclick=()=>{const blob=new Blob([JSON.stringify({title:'AEROVANE V4 — classic material preset',materials:configs},null,2)],{type:'application/json'});const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download='AEROVANE-V4-Material-Preset.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
$('#throttle').oninput=e=>{$('#throttleVal').textContent=e.target.value+'%';};
$('#hover').oninput=e=>{$('#hoverVal').textContent=(e.target.value/100).toFixed(2)+' m';if(+e.target.value>0&&+$('#throttle').value<35){$('#throttle').value=35;$('#throttleVal').textContent='35%'}cue('hydraulic')};
$('#yaw').oninput=e=>{$('#yawVal').textContent=e.target.value+'°';$('#turn').checked=false};
$('#fov').oninput=e=>{perspective.fov=+e.target.value;perspective.updateProjectionMatrix();$('#fovVal').textContent=e.target.value+'°'};
$('#exposure').oninput=e=>{renderer.toneMappingExposure=e.target.value/100;$('#expVal').textContent=renderer.toneMappingExposure.toFixed(2)};
$('#wire').onchange=e=>{allMats.forEach(m=>m.wireframe=e.target.checked);sketchMat.wireframe=e.target.checked};
$('#lift').onclick=()=>{if(!ready)return;const up=+$('#hover').value===0;$('#hover').value=up?80:0;$('#hoverVal').textContent=up?'0.80 m':'0.00 m';$('#throttle').value=up?65:0;$('#throttleVal').textContent=up?'65%':'0%';$('#lift').textContent=up?'Settle / land':'Lift / hover';cue('beep');cue('hydraulic');if($('#haptic').checked&&navigator.vibrate)navigator.vibrate([30,50,30])};
$('#exposure').dispatchEvent(new Event('input'));
$('#reset').onclick=()=>{view('hero');$('#throttle').value=0;$('#throttleVal').textContent='0%';$('#hover').value=0;$('#hoverVal').textContent='0.00 m';$('#yaw').value=0;$('#yawVal').textContent='0°';$('#lift').textContent='Lift / hover';$('#wire').checked=false;allMats.forEach(m=>m.wireframe=false);sketchMat.wireframe=false;configs=structuredClone(defaults);applyMaterials();syncEditor();$('#exposure').value=115;renderer.toneMappingExposure=1.15;$('#expVal').textContent='1.15';$('#fov').value=35;perspective.fov=35;perspective.updateProjectionMatrix();$('#fovVal').textContent='35°';sketch=false;atmosphere(false);setSketch(false)};
$('#collapse').onclick=()=>{const hidden=$('#panelbody').style.display==='none';$('#panelbody').style.display=hidden?'':'none';$('#collapse').textContent=hidden?'−':'+';$('#collapse').setAttribute('aria-expanded',String(hidden))};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#atelier').requestFullscreen()}catch{toast('Fullscreen is not supported in this browser.')}};$('#capture').onclick=()=>{if(!ready)return toast('Please wait for the model to load.');drawScene();renderer.domElement.toBlob(blob=>{if(!blob)return toast('Image export unavailable.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AEROVANE-V4-'+(sketch?'Sketch-'+sketchStyle:night?'Nocturne':'Studio')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('Current 3D view exported.')},'image/png')};$('#print').onclick=()=>window.print();
// Gradual fan spool, damped hover settling and subtle deterministic vibration.
let spool=0,liftHeight=0,liftVelocity=0,yawAngle=0,elapsed=0,paused=false;
let audioCtx=null,master=null,motorGain=null,noiseGain=null,oscillators=[],noiseFilter=null,soundOn=false;
async function soundToggle(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=0;master.connect(audioCtx.destination);const limiter=audioCtx.createDynamicsCompressor();limiter.connect(master);motorGain=audioCtx.createGain();motorGain.gain.value=0;motorGain.connect(limiter);for(let i=0;i<4;i++){const o=audioCtx.createOscillator();o.type=i<2?'sine':'triangle';o.frequency.value=70+i*1.7;o.connect(motorGain);o.start();oscillators.push(o)}const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate);const arr=buffer.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;const noise=audioCtx.createBufferSource();noise.buffer=buffer;noise.loop=true;noiseFilter=audioCtx.createBiquadFilter();noiseFilter.type='lowpass';noiseFilter.frequency.value=700;noiseGain=audioCtx.createGain();noiseGain.gain.value=0;noise.connect(noiseFilter);noiseFilter.connect(noiseGain);noiseGain.connect(limiter);noise.start()}await audioCtx.resume();soundOn=!soundOn;master.gain.setTargetAtTime(soundOn?.35:0,audioCtx.currentTime,.15);$('#sound').textContent=soundOn?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(soundOn));cue('beep')}catch{toast('Audio unavailable in this browser.')}}
function cue(kind){if(!soundOn||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=kind==='beep'?'sine':'triangle';const t=audioCtx.currentTime;o.frequency.setValueAtTime(kind==='beep'?750:140,t);o.frequency.exponentialRampToValueAtTime(kind==='beep'?1000:60,t+.18);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.05,t+.03);g.gain.exponentialRampToValueAtTime(.0001,t+.3);o.connect(g);g.connect(master);o.start();o.stop(t+.32)}
$('#sound').onclick=soundToggle;
function updateMotion(dt){elapsed+=dt;const desired=+$('#throttle').value/100;spool+=(desired-spool)*(1-Math.exp(-dt/1.25));const wanted=+$('#hover').value/100;const a=12*(wanted-liftHeight)-6*liftVelocity;liftVelocity+=a*dt;liftHeight=Math.max(0,liftHeight+liftVelocity*dt);const vib=$('#vibration').checked?spool:0;
model.position.y=liftHeight+vib*.005*Math.sin(elapsed*29);model.rotation.z=vib*.002*Math.sin(elapsed*23);model.rotation.x=vib*.0015*Math.cos(elapsed*19);
if($('#turn').checked){yawAngle+=dt*.13;$('#yaw').value=THREE.MathUtils.radToDeg(yawAngle) %360;$('#yawVal').textContent=Math.round(THREE.MathUtils.radToDeg(yawAngle)%360)+'°'}else{const requested=THREE.MathUtils.degToRad(+$('#yaw').value);let diff=Math.atan2(Math.sin(requested-yawAngle),Math.cos(requested-yawAngle));yawAngle+=diff*(1-Math.exp(-dt*4))}pivot.rotation.y=yawAngle;
rotors.forEach((o,i)=>{const sign=o.userData.counterRotation||((i%2)?1:-1);o.rotation.x=(o.rotation.x+sign*spool*60*dt)%(2*Math.PI)});
$('#actualHeight').textContent=liftHeight.toFixed(2)+' m';$('#actualRPM').textContent=Math.round(spool*573)+' rpm';$('#flightState').textContent=liftHeight>.05?'HOVER STUDY':spool>.03?'FAN SPOOL':'RESTING';
if(audioCtx&&soundOn){const t=audioCtx.currentTime;motorGain.gain.setTargetAtTime(spool*.035,t,.1);noiseGain.gain.setTargetAtTime(spool*.07,t,.15);oscillators.forEach((o,i)=>o.frequency.setTargetAtTime(55+spool*(95+i*4)+i*1.7,t,.15));noiseFilter.frequency.setTargetAtTime(300+spool*1700,t,.15)}
}
document.addEventListener('visibilitychange',()=>{paused=document.hidden;clock.getDelta();if(audioCtx){if(paused)audioCtx.suspend();else if(soundOn)audioCtx.resume()}});
function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.04);if(paused)return;controls.update();if(ready)updateMotion(dt);drawScene()}render();
window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Escape'){$('#throttle').value=0;$('#throttleVal').textContent='0%';$('#hover').value=0;$('#hoverVal').textContent='0.00 m';$('#turn').checked=false;cue('beep')}if(e.key.toLowerCase()==='r')$('#reset').click()});
